name: Training Model Otomatis

# Trigger: Jalan setiap kali ada push ke branch main
on:
  push:
    branches: [ "main" ]

jobs:
  training_job:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Ambil kodingan dari repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Siapkan Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install Library
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow scikit-learn pandas

    # 4. JALANKAN MODEL (VERSI REVISI - WAJIB MLFLOW RUN)
    - name: Train Model with MLflow
      run: |
        # PENTING: Ganti 'Membangun_model' sesuai nama folder kamu di GitHub
        # (Kalau nama foldermu masih 'MLProject', ganti jadi 'cd MLProject')
        cd Membangun_model 
        
        # Perintah ini yang diminta reviewer:
        mlflow run . \
          -P train_data=bank_data_preprocessing.csv \
          -P test_data=bank_data_preprocessing.csv \
          -P target_column=Exited \
          --env-manager=local

    # 5. SIMPAN HASIL
    - name: Archive MLflow Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: hasil-eksperimen-mlruns
        # Sesuaikan path ini juga dengan nama foldermu
        path: Membangun_model/mlruns
